export const states = [
  { label: "Andhra Pradesh", code: "AP" },
  { label: "Arunachal Pradesh", code: "AR" },
  { label: "Assam", code: "AS" },
  { label: "Bihar", code: "BR" },
  { label: "Chhattisgarh", code: "CG" },
  { label: "Goa", code: "GA" },
  { label: "Gujarat", code: "GJ" },
  { label: "Haryana", code: "HR" },
  { label: "Himachal Pradesh", code: "HP" },
  { label: "Jharkhand", code: "JH" },
  { label: "Karnataka", code: "KA" },
  { label: "Kerala", code: "KL" },
  { label: "Madhya Pradesh", code: "MP" },
  { label: "Maharashtra", code: "MH" },
  { label: "Manipur", code: "MN" },
  { label: "Meghalaya", code: "ML" },
  { label: "Mizoram", code: "MZ" },
  { label: "Nagaland", code: "NL" },
  { label: "Odisha", code: "OR" },
  { label: "Punjab", code: "PB" },
  { label: "Rajasthan", code: "RJ" },
  { label: "Sikkim", code: "SK" },
  { label: "Tamil Nadu", code: "TN" },
  { label: "Telangana", code: "TS" },
  { label: "Tripura", code: "TR" },
  { label: "Uttar Pradesh", code: "UP" },
  { label: "Uttarakhand", code: "UK" },
  { label: "West Bengal", code: "WB" },
];

export const domains = [
  { label: "Restaurant", code: "REST" },
  { label: "Retail", code: "RETL" },
  { label: "Information Technology", code: "IT" },
  { label: "Healthcare", code: "HLTH" },
  { label: "Education", code: "EDUC" },
  { label: "Manufacturing", code: "MNFG" },
  { label: "Finance", code: "FIN" },
  { label: "Real Estate", code: "RE" },
  { label: "Transportation", code: "TRANS" },
  { label: "Tourism", code: "TOUR" },
];

export const URL = "http://localhost:8000";
